// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igeisxaffalxscintgqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZWlzeGFmZmFseHNjaW50Z3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzMwMzksImV4cCI6MjA2MDI0OTAzOX0.C4HNAstRTLChSblbR7UxyPlEcRf1xO0U1hHw2mSziYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);